### ISSUE TITLE
Contact Me Here

### ISSUE THREAD

**Issue by Ved-programmer** [Ved-programmer/Ved-programmer#174]

**Comment by Ved-programmer** [comment]
You can contact me here

**Comment by neon-coder** [comment]
hi am neon-coder Actually I have a doubt 

your 5 years older than me but you have forked my readme

**Comment by Ved-programmer** [comment]
so? you are supposed to go to pull requests and then click on the pull request that I made and then scroll down to merge pull request and merge it. 

Edit : Ask Navdeep

**Comment by neon-coder** [comment]
I can’t believe it that you have forked mine

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by neon-coder** [comment]
i can't believe it that you have forked mine 
Actually I follewed you about python.

**Comment by Ved-programmer** [comment]
why?

**Comment by Ved-programmer** [comment]
anyways, now would u accept my pull request?

**Comment by neon-coder** [comment]
ok

**Comment by neon-coder** [comment]
> i can't believe it that you have forked mine
> Actually I follewed you about python.

I don't know for loops I heard from navdeep that you are a pro pythonista that is why I followed you

**Comment by Ved-programmer** [comment]
> > i can't believe it that you have forked mine
> > Actually I follewed you about python.
> 
> I don't know for loops I heard from navdeep that you are a pro pythonista that is why I followed you

k fine
